### ISSUE TITLE
querying local and remote data together seems to break things

### ISSUE THREAD

**Issue by anomaly44** [apollographql/apollo-link-state#154] opened 2017-12-31 14:05 UTC
I'm pretty new to apollo so it might just be me, but it seems there is something weird happening when I try to query from both local and remote sources.
this snippet works as expected
```javascript
const GET_AUTH = gql`
query {
  auth @client {
    adminLevel
  }
}
`;
```
this one does aswell:
```javascript
const GET_AUTH = gql`
query {
  user(id: 1) {
    id
    email
  }
}
`;
```
when I combine them i get: 
`Uncaught (in promise) TypeError: Cannot read property 'auth' of undefined
    at resolver (index.js:26)`

```javascript
const GET_AUTH = gql`
query {
  auth @client {
    adminLevel
  }
  user(id: 1) {
    email
  }
}
`;
```

This is the same pattern as in the apollo-link-state docs where `networkStatus` and `articles` are queried together.

Am I missing something or is this a bug?

**Comment by johannesfritsch** [comment] 2018-01-01 00:04
This seems to be a duplicate of #140

**Comment by peggyrayzis** [comment] 2018-01-02 19:51
Let's move discussion over to #140 :)

**Closed by peggyrayzis** 2018-01-02 19:51 UTC
