### ISSUE TITLE
Apollo is throwing errors when local state and network data is requested in same query 

### ISSUE THREAD

**Issue by akiran** [apollographql/apollo-link-state#178] opened 2018-01-23 13:35 UTC
```
const appQuery = gql`
  query {
    networkStatus @client {
      isConnected
    }
    ping {
      message
    }
  }
`
```
In this snippet networkStatus is local state and ping is network request.
When both are combined, I get this error
```
Unhandled (in react-apollo) Error: Network error: Cannot read property 'networkStatus' of undefined
```

But if I comment networkStatus or ping, it works.

Does this library support quering both  local state and network data in same query ?

**Comment by peggyrayzis** [comment] 2018-01-23 14:03
Duplicate of #140

**Closed by peggyrayzis** 2018-01-23 14:03 UTC

**Comment by KevinDanikowski** [comment] 2018-04-05 06:12
Side note for anyone else having this issue, maybe this will help, I found that by adding a name `graphql(query, { name: "newQueryName", props: ({data:{queryName}})=>({queryName})` resulted in can't read queryName of undefined, when I got rid of the name, it worked.
