### ISSUE TITLE
Missing field [mutationName] in {}, when mutating using @client directive

### ISSUE THREAD

**Issue by mathiasjakobsen** [apollographql/apollo-link-state#160] opened 2018-01-03 15:55 UTC
Then trying to execute any `@client` mutation, I get a warning saying `Missing field updateMemorySelectedFlag in {}`.

<details>
  <summary>Stack Trace</summary>
    <img src="https://user-images.githubusercontent.com/1573748/34527543-206f32f4-f0a6-11e7-8282-c9d2a1a06ef7.png" />
</details><br>

Trying to debug, I went through the stack trying to find out why the `Mutation.updateMemorySelectedFlag` isn't _recognized_, but I simply can not find out why this happens. Any input on what the problem is, with the following code?

```es6

// Container.js

...

const mutation = gql`
  mutation updateMemorySelectedFlag($id: ID!, $selected: Boolean) {
    updateMemorySelectedFlag(id: $id, selected: selected) @client {
      id
      selected
    }
  }
`

export default graphql(mutation, {
  props: ({ mutate }) => {
    updateFlag: (id, selected) => mutate({ variabels: { id, selected }),
  },
})
```
```es6
// resolvers.js

export const defaults = {
}

export const resolvers = {
  Memory: {
    selected: ({ selected }) => selected || false,
  },
  Mutation: {
    updateMemorySelectedFlag: (_, { id, selected }, { cache }) => {
      cache.writeData({ id: `Memory:${id}`, data: { selected: true } })
    },
  },
  Query: {
  },
}
```
```es6
// client.js

import { ApolloClient } from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { setContext } from 'apollo-link-context'
import { withClientState } from 'apollo-link-state'
import { ApolloLink } from 'apollo-link'
import { defaults, resolvers } from './resolvers/root'

export default function configureClient() {
  const cache = new InMemoryCache()

  const httpLink = new HttpLink({
    uri: 'https://webapp.com/graphql',
  })

  const authLink = setContext((_, { headers }) => {
    const token = localStorage.getItem('token')

    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : null,
      },
    }
  })

  const stateLink = withClientState({ resolvers, cache, defaults })

  const client = new ApolloClient({
    cache,
    link: ApolloLink.from([stateLink, authLink, httpLink]),
  })

  return client
}
```

**Comment by Phoenixmatrix** [comment] 2018-01-03 19:41
Your `updateMemorySelectedFlag` mutation needs to return null if it doesn't return anything otherwise.

**Comment by asokani** [comment] 2018-01-04 10:29
I fell into this trap too. There's also this question at StackOverflow: https://stackoverflow.com/questions/48005732/apollo-link-state-cache-writedata-results-in-missing-field-warning

So that means the example at https://github.com/apollographql/apollo-link-state is wrong and the mutation method should return something? Shouldn't that be documented somewhere?

**Comment by mathiasjakobsen** [comment] 2018-01-04 14:36
@Phoenixmatrix great! Thanks 👍  Though, I agree with @asokani - it's not very obvious, that this is required & the error message isn't really giving any hints ¯\_(ツ)_/¯

**Comment by Phoenixmatrix** [comment] 2018-01-04 14:37
Oh for sure, the doc should be updated and the error message clarified. I'm not a contributor though. Just a guy who hit the same issue trying to get you folks unblocked for now :)

**Comment by mathiasjakobsen** [comment] 2018-01-05 12:31
@Phoenixmatrix Oh.. my bad 🐫  Anyways, thank you for helping us out! I'm was about to explode 🤣

**Comment by peggyrayzis** [comment] 2018-01-05 21:53
@mathiasjakobsen If you are specifying a selection set for your mutation return values, you have to return data from your resolver. Otherwise, if you are not specifying a selection set, you must return null since all types in GraphQL are nullable by default (no undefined). I'm going to eventually set it up so it automatically returns null if no return value is specified but I haven't gotten around to it yet.

The error message is an Apollo Client one so not much I can do there for this use case. Since this is resolved, I'm going to close this for now.

**Closed by peggyrayzis** 2018-01-05 21:53 UTC

**Comment by serranoarevalo** [comment] 2018-05-22 14:32
What if I'm returning null and still the mutation is not recognized?

Query:
````ts
export const LOG_USER_IN = gql`
  mutation logUserIn($token: String!) {
    logUserIn(token: $token) @client
  }
`;
````
Mutation:

````ts
logUserIn: (
    { parent }: { parent: any },
    { token }: { token: string },
    { cache }: { cache: ApolloCache<any> }
) => {
    // localStorage.setItem("jwt", token);
    const data = {
        user: { __typename: "User", isLoggedIn: true, token }
    };
    cache.writeData({ data });
    return null;
}
````
Trigger

````ts
...
proxy.writeQuery({
    data: {
        token: facebookConnect.token
    },
    query: LOG_USER_IN
});
````

**Comment by bennypowers** [comment] 2018-07-10 20:36
I had a helluva time debugging a similar problem, and I made it through, so I'd like to share my notes for the benefit of ~future me~ people who googled this error:

I have a lot of resolvers that were like:

```js
export const updateUser = (_, user, { cache }) => {
  const { user: cached } = cache.readQuery({ query });

  const data = { user: {
    ...defaultUser,
    ...cached,
    ...omitUndefined(user),
  } };

  cache.writeData({ data });
  return data;
};
```
the problem here was to return the `data` object, not the `user` object. 

The working version looks like this:

```js
const omitUndefined = mapOmit(isDefined);

export const updateUser = (_, args, { cache }) => {
  const { user: cached } = cache.readQuery({ query });

  const user = {
    ...defaultUser,
    ...cached,
    ...omitUndefined(args),
  };

  cache.writeData({ data: { user } });
  return user;
};
```

note that i renamed the second parameter to `args` so that it wouldn't shadow the return value.

**Comment by adidaas** [comment] 2018-11-21 18:31
So I've had the same error and just found the cause was ridiculously simple. I imported my resolvers incorrectly and forgot to wrap them in {}.

Just in case anyone else runs googles this issue; don't make the same simple(idiotic) mistake I did.

**Comment by yodaheis** [comment] 2019-03-29 08:42
@adidaas Thanks for putting your case, I made the same mistake. Wish the errors were as helpful as with apollo server.
