### ISSUE TITLE
Mixing client and server state in query leads to error

### ISSUE THREAD

**Issue by benhjames** [apollographql/apollo-link-state#140] opened 2017-12-26 02:01 UTC
Let's say I have a query like this:

```
query StoryLayout($storyId: ID!) {
  tutorial @client
  story(id: $storyId) {
    id
  }
}
```

This throws with the following error:

```
TypeError: Cannot read property 'tutorial' of undefined
    at resolver (/project/node_modules/apollo-link-state/lib/index.js:26:66)
    at /project/node_modules/apollo-link-state/node_modules/graphql-anywhere/lib/graphql-async.js:132:32
    at step (/project/node_modules/apollo-link-state/node_modules/graphql-anywhere/lib/graphql-async.js:31:23)
    at Object.next (/project/node_modules/apollo-link-state/node_modules/graphql-anywhere/lib/graphql-async.js:12:53)
    at /project/node_modules/apollo-link-state/node_modules/graphql-anywhere/lib/graphql-async.js:6:71
    at new Promise (<anonymous>)
    at __awaiter (/project/node_modules/apollo-link-state/node_modules/graphql-anywhere/lib/graphql-async.js:2:12)
    at executeField (/project/node_modules/apollo-link-state/node_modules/graphql-anywhere/lib/graphql-async.js:119:12)
    at /project/node_modules/apollo-link-state/node_modules/graphql-anywhere/lib/graphql-async.js:73:48
    at step (/project/node_modules/apollo-link-state/node_modules/graphql-anywhere/lib/graphql-async.js:31:23)
```

Removing either the `tutorial @client` or `story` field makes the issue go away.

Here's the offending code above for convenience!

https://github.com/apollographql/apollo-link-state/blob/1c2d5fd275a8208b68cdab2aa32f4cdc3cc05030/packages/apollo-link-state/src/index.ts#L51-L61

Interestingly, `rootValue` in the above function only contains the value for the `story` field, and not the `tutorial` field. I've been trying to track down why, but could do with some help! :)

**Comment by evenchange4** [comment] 2017-12-28 01:36
@benhjames Thanks you for clarifying the issue, 
I have run into the same problem with combine server side query and the `@client` one.
```diff
query todosQuery {
  todos {
    id
    title
    completed
  }
+ filter @client
}
```

Here is a repository(bugfix/state-140 branch) to reproduce it and the output is:
https://github.com/evenchange4/todomvc-subscriptions/pull/11

```cmd
$ yarn install
$ yarn start
@todomvc-subscriptions/web: (node:19542) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
    at resolver (/todomvc-subscriptions/node_modules/apollo-link-state/lib/index.js:26:66)
```

**Comment by peggyrayzis** [comment] 2018-01-09 20:06
Thanks for reporting! I was able to reproduce your error with a failing test case and will work on trying to fix it today.

**Comment by adam-s** [comment] 2018-01-17 02:43
I'm not sure if this needs another issue created as it might be similar to this. Using the [Apollo Universal Starter Kit](https://github.com/adam-s/apollo-universal-starter-kit/tree/apollo-link-state), I started down the path of removing Redux as the store since Apollo with Apollo Link State should work. If it has rendered on a different page `(/posts`) it works fine including when navigating to the `/users` page. However, if the page is reloaded and an attempt is made to render on the server at path `/users`, the one GraphQL definition with the @client directive will cause errors to be thrown.

> ServerError: GraphQL error: Cannot query field "getValue" on type "Query". GraphQL error: Unknown directive "client".
new
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/errors/ApolloError.js:34:28
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:266:41
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:646:17
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:645:18
QueryManager.broadcastQueries
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:640:22
Object.next
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-client/core/QueryManager.js:672:31
SubscriptionObserver.next
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/zen-observable/zen-observable.js:154:14
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-link-dedup/lib/dedupLink.js:49:76
Object.next
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-link-dedup/lib/dedupLink.js:49:43
SubscriptionObserver.next
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/zen-observable/zen-observable.js:154:14
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-link-batch/lib/batching.js:58:37
Object.next
at /home/adam/PhpstormProjects/apollo-universal-starter-kit/node_modules/apollo-link-batch/lib/batching.js:56:25

Here are the changes that I committed to test it. https://github.com/adam-s/apollo-universal-starter-kit/commit/cb1da95ddf9a392671e0149111747f18ddeb2482

**Comment by brunobasto** [comment] 2018-01-25 00:31
I'm interested on this fix as well :)

**Comment by oqx** [comment] 2018-01-25 22:47
I'd love to see a fix for this as well. I was converting all my Redux code when this issue popped up.

**Comment by krokofant** [comment] 2018-01-28 23:39
It's unfortunate that features described [in the docs](https://www.apollographql.com/docs/link/links/state.html#start) doesn't work.

**Comment by jfreixa** [comment] 2018-01-30 12:01
Instead of an error now throws a warning.
Query:
https://cl.ly/2u3V3v2p1f2t
Warning:
https://cl.ly/423U2D3G1b1C
Default state:
https://cl.ly/1Y1R2j39212q

**Comment by akiran** [comment] 2018-02-02 06:09
@peggyrayzis I am trying to fix this issue and send a PR.

Here client fields are removed to process server query.
https://github.com/apollographql/apollo-link-state/blob/master/packages/apollo-link-state/src/index.ts#L63

Similarly, We need to get client only query and pass it [here](https://github.com/apollographql/apollo-link-state/blob/master/packages/apollo-link-state/src/index.ts#L95) to make apollo link state process only client fields.

We will need getDirectivesFromDocument utility function you described here https://github.com/apollographql/apollo-client/issues/2884 to accomplish this

Am I going in the right direction to fix this issue ?

**Comment by ostrebler** [comment] 2018-02-13 01:48
Same issue here.

**Comment by udgirpratik** [comment] 2018-02-13 06:51
Hello Team, Any Plans or any updates for this issue

**Comment by akiran** [comment] 2018-02-13 07:25
PR is open for this issue 
https://github.com/apollographql/apollo-link-state/pull/193

**Comment by vic08** [comment] 2018-02-19 10:03
is this bug still present?

**Comment by coodoo** [comment] 2018-02-19 10:04
Yes.

**Comment by santiag00** [comment] 2018-03-06 11:01
Same issue here

**Comment by danielmahon** [comment] 2018-03-11 03:06
Same issue here following docs

**Comment by peggyrayzis** [comment] 2018-03-14 03:07
Closed via #193

**Closed by peggyrayzis** 2018-03-14 03:07 UTC

**Comment by jwdinker** [comment] 2018-04-29 21:36
@peggyrayzis I am also still seeing this with apollo boost.

**Comment by sjnonweb** [comment] 2018-06-22 13:58
I'm also facing this problem with apollo-boost

**Comment by 100alkis** [comment] 2018-06-28 13:16
@peggyrayzis I'm facing the same with an ApolloClient setup (without apollo-boost). Had to create a dummy query resolver like @mikkoh said to make it work.

**Comment by APZelos** [comment] 2018-06-28 13:17
@peggyrayzis I'm facing the same with an ApolloClient setup (without apollo-boost). Had to create a dummy query resolver like @mikkoh said to make it work.

**Comment by ralphchristianeclipse** [comment] 2018-07-11 19:40
still having this issue too

there are some keys that makes it undefined

**Comment by bagratinho** [comment] 2019-02-15 22:43
> I'd love to see a fix for this as well. I was converting all my Redux code when this issue popped up.

haha, same here

**Comment by bagratinho** [comment] 2019-02-15 22:45
I have similar issue, my combined query will work but will show only the default value for the local field and will not react if the local data is mutated, instead it will do so when I query just `@client` fields
