### ISSUE TITLE
Retrieving data from a HttpLink and withLocalState throws an error

### ISSUE THREAD

**Issue by jfreixa** [apollographql/apollo-link-state#169] opened 2018-01-16 16:08 UTC
I'm using ApolloLink.from to merge 2 links one HttpLink and the other withLocaleState. When I'm requesting data from LocalState alone works fine and also when I'm requesting data from httplink alone. The issue happens when I request from the 2 places at the same time.
**Intended outcome:**
Recieve the data as requested
**Actual outcome:** 
Console message:
DOMException: Failed to execute 'postMessage' on 'Window': TypeError: Cannot read property 'todos' of undefined could not be cloned.
**How to reproduce the issue:**
Respository with the issue reproduced:
https://github.com/jfreixa/apollo-link-state/tree/master/examples/todo
Error in production:
https://jfreixa.github.io/apollo-link-state/

**Comment by peggyrayzis** [comment] 2018-01-16 17:08
Can you please post your query? I'm thinking this is a duplicate of #140, the fix should be out some time this week.

**Comment by jfreixa** [comment] 2018-01-16 18:32
This file
https://github.com/jfreixa/apollo-link-state/blob/master/examples/todo/src/containers/FilterLink.js
`const VISIBILITY_QUERY = gql`
  {
    visibilityFilter @client
    Fake {
      firstName
    }
  }
`;`

**Comment by peggyrayzis** [comment] 2018-01-16 18:57
Yup, this is the same issue. Closing in favor of #140

**Closed by peggyrayzis** 2018-01-16 18:57 UTC
